# Generated by Django 5.0.8 on 2024-09-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField()),
                ('scheme_name', models.CharField(max_length=255)),
            ],
        ),
    ]
