# Generated by Django 5.0.8 on 2024-08-20 09:40

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Budget Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[expenses.models.validate_positive], verbose_name='Budget Amount')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=50, verbose_name='Budget Category')),
                ('description', models.TextField(blank=True, verbose_name='Budget Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Expense Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[expenses.models.validate_positive], verbose_name='Expense Amount')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=50, verbose_name='Expense Category')),
                ('description', models.TextField(blank=True, verbose_name='Expense Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Income Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[expenses.models.validate_positive], verbose_name='Income Amount')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=50, verbose_name='Income Source')),
                ('description', models.TextField(blank=True, verbose_name='Income Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Investment Title')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15, validators=[expenses.models.validate_positive], verbose_name='Amount Invested')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[expenses.models.validate_positive], verbose_name='Current Value')),
                ('date_invested', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, verbose_name='Investment Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
