# Generated by Django 5.0.8 on 2024-09-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='due',
            old_name='due_date',
            new_name='borrowed_on',
        ),
    ]
