# Generated by Django 5.0.8 on 2024-09-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirementgoal',
            name='inflation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
